'use client'

import { PDFPage, NotePage } from '@/types'
import { generateId } from '@/lib/utils'

function cleanPdfTextCompletely(text: string): string {
  let result = text

  const pageNumberPatterns = [
    /^\s*(Page|P\.?|p\.?|ページ|No\.?|№|#)\s*\d+(\s*[\/\-]\s*\d+)?\s*$/gim,
    /^\s*\d+\s*[\/\-]\s*\d+\s*$/gm,
    /^\s*\d+\s*$/gm,
    /\b(Page|P\.?|p\.?|ページ|No\.?|№|#)\s*\d+(\s*[\/\-]\s*\d+)?\b/gi,
    /\[\s*\d+\s*\]/g,
    /\(\s*\d+\s*\)/g,
    /---\s*\d+\s*---/g,
    /===\s*\d+\s*===/g,
    /\*\*\*\s*\d+\s*\*\*\*/g,
    /[-=*]{2,}\s*\d+\s*[-=*]{2,}/g,
  ]
  pageNumberPatterns.forEach(pattern => {
    result = result.replace(pattern, '')
  })

  const watermarkPatterns = [
    /©.*?\d{4}/g,
    /Copyright.*?/gi,
    /All Rights Reserved/gi,
    /www\..+?\.(com|jp|net|org|co\.jp|ac\.jp|go\.jp)/gi,
    /https?:\/\/[^\s]+/g,
    /[○●○●]{2,}/g,
    /[■□■□]{2,}/g,
    /[◆◇◆◇]{2,}/g,
    /[※★☆]{2,}/g,
    /[△▽△▽]{2,}/g,
    /[◇◇◇◇]{2,}/g,
    /[□□□□]{2,}/g,
    /[○○○○]{2,}/g,
    /[●●●●]{2,}/g,
    /[■■■■]{2,}/g,
    /[▽▽▽▽]{2,}/g,
    /[△△△△]{2,}/g,
    /[☆☆☆☆]{2,}/g,
    /[★★★★]{2,}/g,
    /[＃＃＃＃]{2,}/g,
    /[＊＊＊＊]{2,}/g,
    /[＝＝＝＝]{2,}/g,
    /[－－－－]{2,}/g,
    /[＿＿＿＿]{2,}/g,
    /[・・・・]{2,}/g,
    /[、、、、]{2,}/g,
    /[。。。。]{2,}/g,
    /[「「「「]{2,}/g,
    /[」」」」]{2,}/g,
    /[（（（（]{2,}/g,
    /[））））]{2,}/g,
    /[─-╿▀-▟]{3,}/g,
    /[■-◿]{3,}/g,
    /株式会社.*?(?=\n|$)/g,
    /有限会社.*?(?=\n|$)/g,
    /大学.*?(?=\n|$)/g,
    /学部.*?(?=\n|$)/g,
    /学科.*?(?=\n|$)/g,
    /研究科.*?(?=\n|$)/g,
    /研究室.*?(?=\n|$)/g,
    /教授.*?(?=\n|$)/g,
    /准教授.*?(?=\n|$)/g,
    /講師.*?(?=\n|$)/g,
    /助教.*?(?=\n|$)/g,
    /ロゴ.*?(?=\n|$)/g,
    /logo.*?(?=\n|$)/gi,
    /trademark.*?(?=\n|$)/gi,
    /™.*?(?=\n|$)/g,
    /年月日.*?(?=\n|$)/g,
    /日付.*?(?=\n|$)/g,
    /作成日.*?(?=\n|$)/g,
    /更新日.*?(?=\n|$)/g,
    /配布日.*?(?=\n|$)/g,
    /改訂日.*?(?=\n|$)/g,
    /title.*?(?=\n|$)/gi,
    /タイトル.*?(?=\n|$)/g,
    /[A-Za-z]{2,4}\d{2,4}[A-Za-z]?/g,
    // PPT slide markers
    /Slide\s*\d+/gi,
    /スライド\s*\d+/g,
    /\d+\s*\/\s*\d+\s*(ページ|頁|page|スライド)?/gi,
    // Date formats in headers/footers
    /\d{4}[\/\-\.年]\d{1,2}[\/\-\.月]\d{1,2}日?/g,
    /\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4}/g,
    // Single char repeated (extraction artifacts)
    /(.)\1{8,}/g,
  ]
  watermarkPatterns.forEach(pattern => {
    result = result.replace(pattern, '')
  })

  result = result.replace(/(\S)\1{3,}/g, '')

  const referencePatterns = [
    /参考文献[:：].*?(?=\n|$)/g,
    /引用[:：].*?(?=\n|$)/g,
    /参考資料[:：].*?(?=\n|$)/g,
    /文献[:：].*?(?=\n|$)/g,
  ]
  referencePatterns.forEach(pattern => {
    result = result.replace(pattern, '')
  })

  result = filterEnglishWatermarkLines(result)

  result = result.replace(/\n{3,}/g, '\n\n')
  result = result.replace(/[ \t]+/g, ' ')

  return result.trim()
}

function filterEnglishWatermarkLines(text: string): string {
  const lines = text.split('\n')
  const filteredLines: string[] = []

  const englishWatermarkKeywords = [
    'Downloaded by', 'Strictly Confidential', 'Powered by', 'WPS',
    'Standard Version', 'Premium', 'Free Trial', 'Evaluation',
    'Demo', 'Sample', 'For internal use only', 'Confidential',
    'Property of', 'Not for distribution', 'Watermark', 'Unregistered',
    'Registered to', 'Created with', 'Generated by', 'Produced by',
    'Printed from', 'Document number', 'Doc ID', 'File ID',
    'Presentation made with', 'Slide made with', 'PowerPoint',
    'Keynote', 'Google Slides', 'SlideShare', 'Prezi',
    'www.', '.com', '.net', '.org', 'http', 'https',
    '©', 'Copyright', 'All rights reserved', 'TM', 'Trademark'
  ]

  for (const line of lines) {
    const trimmedLine = line.trim()

    if (!trimmedLine) {
      filteredLines.push('')
      continue
    }

    let isWatermark = false

    for (const keyword of englishWatermarkKeywords) {
      if (trimmedLine.toLowerCase().includes(keyword.toLowerCase())) {
        isWatermark = true
        break
      }
    }

    if (!isWatermark) {
      const englishCharRatio = (trimmedLine.match(/[a-zA-Z]/g) || []).length / trimmedLine.length
      const japaneseCharRatio = (trimmedLine.match(/[぀-ヿ㐀-䶿一-鿿]/g) || []).length / trimmedLine.length

      if (englishCharRatio > 0.7 && japaneseCharRatio < 0.1) {
        if (trimmedLine.length < 50) {
          isWatermark = true
        }
      }
    }

    if (!isWatermark) {
      filteredLines.push(line)
    }
  }

  return filteredLines.join('\n')
}

export function createFullTextStream(pages: PDFPage[]): string {
  const allText = pages.map(p => p.text).join('\n')
  return cleanPdfTextCompletely(allText)
}

export function splitTextIntoChunks(text: string, chunkSize: number = 2000): string[] {
  const chunks: string[] = []
  const sentences = text.split(/(?<=[。！？.!?])\s+/)
  let currentChunk = ''

  for (const sentence of sentences) {
    if (currentChunk.length + sentence.length <= chunkSize) {
      currentChunk += (currentChunk ? ' ' : '') + sentence
    } else {
      if (currentChunk) chunks.push(currentChunk.trim())
      currentChunk = sentence
    }
  }

  if (currentChunk) chunks.push(currentChunk.trim())
  return chunks
}

export const DETAIL_EXTRACTION_PROMPT = `以下の段落から、すべての詳細を抽出してください。
【絶対条件】
- コアとなる定義、数式、重要な結論を絶対に削除しないでください
- 要約を書かないでください
- 詳細な知識リストを作成してください
- 各ポイントは明確に分けて記述してください
- 「第Xページ」や「内容は...から」といったページ言及は絶対に禁止します

出力形式：
- 各知識ポイントを箇条書きでリスト化してください
- 重要な概念は太字で強調してください
- 数式や定義は正確に転記してください`

export const FINAL_SYNTHESIS_PROMPT = `以下の詳細リストを再編成し、学科の論理に従って（出現順ではなく）同類項をまとめ、最終的な深層学習ノートを生成してください。

【絶対条件】
- あなたの最優先事項は**完全性**です
- もし文字数制限で一度に完成できない場合は、まずアウトラインをリストしてください。私はあなたに部分的に埋めてもらいます
- ノートが少し長くなっても、資料内のどんな知識ポイントも漏らさないでください
- 「第Xページ」や「内容は...から」といったページ言及は絶対に禁止します

【出力構成】
1. 目次（Table of Contents）
2. コアコンセプト：この資料の最も重要なポイントを3〜5語で要約
3. 論理的連鎖：関連コンテンツを統合し、「なぜ-何-どのように」のロジックで整理
4. 本文ノート (Markdown)：複数レベルの見出し、コードブロック、太字の強調、タスクリストを使用
5. 自己テスト質問：内容に基づいた思考問題を3つ提示`

// ========== Content-aware note generation (replaces hardcoded templates) ==========

function detectTitle(lines: string[]): string {
  for (let i = 0; i < Math.min(15, lines.length); i++) {
    const line = lines[i].trim()
    if (line.length > 5 && line.length < 100 &&
        !/^[\d\s\.\-、,，・※*\-—]+$/.test(line) &&
        !line.endsWith('。') && !line.endsWith('、') && !line.endsWith('，') &&
        line.replace(/[「」『』【】]/g, '').length > 4) {
      return line
    }
  }
  return '学習ノート'
}

function isHeading(line: string): boolean {
  const t = line.trim()
  if (t.length < 3 || t.length > 80) return false
  if (t.endsWith('。') || t.endsWith('！') || t.endsWith('？')) return false
  if (/^[\d\s\.\-、,，・※\*\-—]+$/.test(t)) return false

  if (/^(\d+[\.\、\)]\s*|第[一二三四五六七八九十\d]+[章節节課回]\s*|Section\s*\d+|Chapter\s*\d+|■|□|◆|◇|▼|▽|◎|●|○)/.test(t)) return true
  if (t.length < 40 && !/[、，。「」『』]/.test(t)) return true
  if (/[概要紹介説明結論まとめ目標目的背景方法結果考察参考資料内容意味定義特徴分類種類意義課題展望].*[：:]?$/.test(t) && t.length < 60) return true
  if (/^[①②③④⑤⑥⑦⑧⑨⑩⑪⑫⑬⑭⑮⑯⑰⑱⑲⑳]/.test(t)) return true

  return false
}

function splitIntoSections(lines: string[]): Array<{ heading: string; content: string[] }> {
  const sections: Array<{ heading: string; content: string[] }> = []
  let currentHeading = ''
  let currentContent: string[] = []

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) continue

    if (isHeading(trimmed)) {
      if (currentContent.length > 0) {
        sections.push({ heading: currentHeading || 'はじめに', content: currentContent })
      }
      currentHeading = trimmed
      currentContent = []
    } else {
      currentContent.push(line)
    }
  }

  if (currentContent.length > 0) {
    sections.push({ heading: currentHeading || '本文', content: currentContent })
  }

  if (sections.length === 0 && lines.length > 0) {
    sections.push({ heading: '本文', content: lines.slice(0, 200) })
  }

  return sections
}

function extractAutoKeyTerms(text: string): string[] {
  const terms = new Map<string, number>()

  const kanjiCompounds = text.match(/[一-鿿]{2,5}/g)
  if (kanjiCompounds) {
    for (const k of kanjiCompounds) {
      if (/^[年月日時分秒回度番号第次大小多少高低長短新旧好坏東西南北中上下左右内外前後]$/.test(k)) continue
      if (/^(これ|それ|あれ|この|その|あの|ここ|そこ|あそこ|こちら|そちら|あちら|どの|どこ|どちら)$/.test(k)) continue
      terms.set(k, (terms.get(k) || 0) + 1)
    }
  }

  const katakanaWords = text.match(/[゠-ヿ]{2,6}/g)
  if (katakanaWords) {
    for (const kw of katakanaWords) {
      if (/^[ァィゥェォッャュョヮヶー]+$/.test(kw)) continue
      terms.set(kw, (terms.get(kw) || 0) + 3)
    }
  }

  const brackets = text.match(/[「『（(]([^」』）)]{1,15})[」』）)]/g)
  if (brackets) {
    for (const b of brackets) {
      const inner = b.replace(/[「『（(」』）)\]]/g, '')
      if (inner.length >= 2 && inner.length <= 15) {
        terms.set(inner, (terms.get(inner) || 0) + 2)
      }
    }
  }

  return Array.from(terms.entries())
    .filter(([_, count]) => count >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([term]) => term)
}

function extractContext(text: string, term: string): string {
  const idx = text.indexOf(term)
  if (idx === -1) return ''
  const start = Math.max(0, idx - 10)
  const end = Math.min(text.length, idx + term.length + 50)
  const snippet = text.slice(start, end).replace(/\n/g, ' ')
  return snippet
}

function scoreSentence(s: string): number {
  let score = 0
  if (s.length > 30 && s.length < 250) score += 1
  if (/\d/.test(s)) score += 1.5 // numbers = facts/data
  if (/[（(][^)）]+[)）]/.test(s)) score += 1 // definitions in parens
  if (/は|が|とは|である|重要な|ポイント|定義|意味|特徴|分類|種類|方法|結果|原因|目的|課題|必要|ポイント/.test(s)) score += 1
  if (/[！!?？]/.test(s)) score += 0.5 // engaging sentences
  // Very short lines are usually garbage
  if (s.length < 10) score -= 5
  // Lines that are just numbers/symbols
  if (/^[\d\s\.\-\/、,，・※\*]+$/.test(s)) score -= 5
  return score
}

function extractKeySentences(text: string, maxCount: number = 6): string[] {
  const raw = text.split(/[。！？.!?\n]/)
    .map(s => s.trim())
    .filter(s => s.length > 5)

  if (raw.length === 0) return []

  // Deduplicate
  const seen = new Set<string>()
  const unique = raw.filter(s => {
    const key = s.slice(0, 20)
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })

  const scored = unique.map(s => ({ s, score: scoreSentence(s) }))
  scored.sort((a, b) => b.score - a.score)
  const top = scored.slice(0, maxCount).map(x => x.s)

  // Restore original order
  return top.sort((a, b) => text.indexOf(a) - text.indexOf(b))
}

function buildContentSummary(lines: string[]): string {
  const sections = splitIntoSections(lines)
  if (sections.length === 0) return ''

  let output = ''

  // Table of contents
  const headings = sections.map(s => s.heading).filter(h => h)
  if (headings.length > 1) {
    output += `**構成:** `
    output += headings.slice(0, 10).join(' → ')
    if (headings.length > 10) output += ` ...他${headings.length - 10}セクション`
    output += `\n\n`
  }

  for (const section of sections) {
    const body = section.content.join(' ')
    const keySentences = extractKeySentences(body, 5)

    if (keySentences.length === 0) continue

    output += `## ${section.heading}\n\n`
    for (const s of keySentences) {
      output += `- ${s}\n`
    }
    output += '\n'
  }

  return output
}

function generateSelfTestQuestions(text: string): string {
  const lines = text.split('\n').filter(l => l.trim())
  const sections = splitIntoSections(lines)
  const headings = sections.map(s => s.heading).filter(h => h && h !== '本文' && h !== 'はじめに')

  const qa: Array<{ q: string; a: string }> = []

  qa.push({
    q: 'この資料の主題は何ですか？重要なポイントを3つ挙げて説明してください。',
    a: pickAnswer(text, 3, 5)
  })

  if (headings.length > 0) {
    const secContent = sections.find(s => s.heading === headings[0])
    qa.push({
      q: `${headings[0]}の要点を自分の言葉で説明してみましょう。`,
      a: pickAnswer(secContent ? secContent.content.join(' ') : text, 2, 4)
    })
  }

  if (headings.length > 1) {
    qa.push({
      q: `${headings[1]}の内容と全体のテーマとの関連性を考察してください。`,
      a: pickAnswer(text, 2, 3)
    })
  }

  if (qa.length < 3) {
    qa.push({ q: 'この資料から学んだことを簡潔にまとめてください。', a: pickAnswer(text, 2, 4) })
  }

  return qa.map((item, i) => {
    let out = `${i + 1}. ${item.q}\n`
    if (item.a) {
      out += `   *解答例：${item.a}*\n`
    }
    return out
  }).join('\n')
}

function pickAnswer(text: string, minSentences: number, maxSentences: number): string {
  const sentences = text.split(/[。！？.!?]/)
    .map(s => s.trim())
    .filter(s => s.length > 15 && s.length < 200)

  if (sentences.length === 0) return ''

  const picked: string[] = []
  const step = Math.max(1, Math.floor(sentences.length / maxSentences))

  for (let i = 0; i < sentences.length && picked.length < maxSentences; i += step) {
    picked.push(sentences[i])
  }

  return picked.slice(0, maxSentences).join('。') + '。'
}

// ========== Reading & annotation enrichment ==========

const READING_DICT: Record<string, string> = {
  '齟齬': 'そご', '齷齪': 'あくせく', '軋轢': 'あつれき', '払拭': 'ふっしょく',
  '喧伝': 'けんでん', '喧噪': 'けんそう', '諫言': 'かんげん', '諫止': 'かんし',
  '邂逅': 'かいこう', '蹉跌': 'さてつ', '蹂躙': 'じゅうりん', '躊躇': 'ちゅうちょ',
  '朦朧': 'もうろう', '斡旋': 'あっせん', '瑕疵': 'かし', '綻び': 'ほころび',
  '綺麗': 'きれい', '籠絡': 'ろうらく', '籠城': 'ろうじょう', '緻密': 'ちみつ',
  '繚乱': 'りょうらん', '繋がり': 'つながり', '敷衍': 'ふえん', '洒脱': 'しゃだつ',
  '逼る': 'せまる', '逼迫': 'ひっぱく', '邁進': 'まいしん', '蹴る': 'ける',
  '謳歌': 'おうか', '謬見': 'びゅうけん', '謬る': 'あやまる', '蹲る': 'うずくまる',
  '瀕死': 'ひんし', '瀕する': 'ひんする', '屠る': 'ほふる', '屠殺': 'とさつ',
  '殆ど': 'ほとんど', '悉く': 'ことごとく', '悉皆': 'しっかい', '忽ち': 'たちまち',
  '暫時': 'ざんじ', '漸く': 'ようやく', '屡々': 'しばしば', '僅か': 'わずか',
  '厳か': 'おごそか', '蔑ろ': 'ないがしろ', '蔑視': 'べっし', '羞恥': 'しゅうち',
  '奢侈': 'しゃし', '刮目': 'かつもく', '箝口': 'かんこう', '箝制': 'かんせい',
  '喧しい': 'やかましい', '嘩しい': 'かまびすしい', '諍い': 'いさかい',
  '均衡': 'きんこう', '是正': 'ぜせい', '脆弱': 'ぜいじゃく', '遵守': 'じゅんしゅ',
  '普遍': 'ふへん', '膨大': 'ぼうだい', '冥利': 'みょうり', '刹那': 'せつな',
  '漸進': 'ぜんしん', '漸次': 'ぜんじ', '蓋然性': 'がいぜんせい', '必然': 'ひつぜん',
}

const CN_ANNOTATION_DICT: Record<string, string> = {
  'イノベーション': '创新',
  'ガバナンス': '治理',
  'コンプライアンス': '合规',
  'レジリエンス': '韧性/抗压能力',
  'ガバメント': '政府',
  'コモディティ': '大宗商品',
  'インセンティブ': '激励/动机',
  'マネタイズ': '变现',
  'サステナビリティ': '可持续性',
  'ダイバーシティ': '多样性',
  'インクルージョン': '包容性',
  'エコシステム': '生态系统',
  'プラットフォーム': '平台',
  'グローバリゼーション': '全球化',
  'デジタルトランスフォーメーション': '数字化转型',
  'メタバース': '元宇宙',
  'ブロックチェーン': '区块链',
  'サイバーセキュリティ': '网络安全',
  'レバレッジ': '杠杆',
  'ポートフォリオ': '投资组合',
  'ボラティリティ': '波动性',
  'コーポレート': '企业/公司',
  'コンソーシアム': '联盟/联合体',
  'フレームワーク': '框架',
  'アルゴリズム': '算法',
  'プロトコル': '协议',
  'インフラ': '基础设施',
  'アジェンダ': '议程',
  'コンセンサス': '共识',
  'シナジー': '协同效应',
  'スキーム': '方案/机制',
  'パラダイム': '范式',
  'アセット': '资产',
  'キャッシュフロー': '现金流',
  'ステークホルダー': '利益相关方',
  'ガイドライン': '指导方针',
  'ベンチマーク': '基准/标杆',
  'オルタナティブ': '替代方案',
  'ナレッジ': '知识',
  'ソリューション': '解决方案',
  'オペレーション': '运营',
  'マネジメント': '管理',
  'ストラテジー': '战略',
  'ポリシー': '政策',
  'イニシアチブ': '倡议',
  'セクター': '领域/部门',
  'メカニズム': '机制',
}

function enrichText(text: string): string {
  let result = text

  for (const [kanji, reading] of Object.entries(READING_DICT)) {
    const escaped = kanji.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const regex = new RegExp(`(?<![（(\\w])${escaped}(?![）)])`, 'g')
    result = result.replace(regex, `${kanji}（${reading}）`)
  }

  for (const [word, cn] of Object.entries(CN_ANNOTATION_DICT)) {
    const regex = new RegExp(`(?<![（(])${word}(?!（中文|[）)])`, 'g')
    let count = 0
    result = result.replace(regex, (match) => {
      count++
      if (count === 1) return `${match}（中文：${cn}）`
      return match
    })
  }

  return result
}

function generateStructuredNotes(fullText: string, pageCount: number): string {
  // Split and deduplicate lines (PPT PDFs often have repeated headers/footers)
  const allLines = fullText.split('\n').map(l => l.trim()).filter(l => l.length > 0)
  const seen = new Set<string>()
  const lines = allLines.filter(l => {
    const key = l.slice(0, 30)
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
  if (lines.length === 0) return '有効なテキストが見つかりませんでした。'

  const title = detectTitle(lines)
  const keyTerms = extractAutoKeyTerms(fullText)
  const selfTestQ = generateSelfTestQuestions(fullText)

  let output = `# ${title}\n\n`
  output += `**ページ数:** ${pageCount}ページ | **文字数:** ${fullText.length}文字\n\n---\n\n`

  // Key concepts section
  if (keyTerms.length > 0) {
    output += `## 核心キーワード\n\n`
    for (const term of keyTerms.slice(0, 12)) {
      const ctx = extractContext(fullText, term)
      output += `- **${term}**${ctx ? ` — ${ctx}` : ''}\n`
    }
    output += '\n---\n\n'
  }

  // Section-by-section refined content
  output += buildContentSummary(lines)

  // Self-test questions
  if (selfTestQ.trim()) {
    output += `---\n\n## 自己確認問題\n\n${selfTestQ}\n`
  }

  return output
}

// ========== Main entry point ==========

export function generateNotesLocal(pages: PDFPage[]): NotePage[] {
  const fullText = createFullTextStream(pages)
  const chunks = splitTextIntoChunks(fullText, 2000)

  const notePages: NotePage[] = []

  if (chunks.length === 0) {
    notePages.push({
      pageNumber: 1,
      originalContent: '',
      noteContent: '有効なコンテンツがありませんでした。'
    })
    return notePages
  }

  const structuredNotes = generateStructuredNotes(fullText, pages.length)

  notePages.push({
    pageNumber: 1,
    originalContent: fullText,
    noteContent: structuredNotes
  })

  return notePages
}

